# Generated by Django 4.2.2 on 2023-06-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data1', models.CharField(max_length=100)),
                ('data2', models.CharField(max_length=100)),
                ('k', models.CharField(max_length=100)),
            ],
        ),
    ]
